const std = @import("std");
const types = @import("types.zig");

const RepoInfo = types.RepoInfo;
const ProjectConfig = types.ProjectConfig;
const FileCheck = types.FileCheck;
const DependencyCheck = types.DependencyCheck;
const ResolvedTool = types.ResolvedTool;

pub fn renderProject(allocator: std.mem.Allocator, info: RepoInfo) ![]const u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);
    try out.print(allocator, "project:\n\ntools:\nnode {s}\n{s} {s}\n", .{ info.node, info.package_manager, info.package_manager_version });
    if (info.compose_files.items.len > 0) {
        try out.print(allocator, "\nservices:\n", .{});
        for (info.compose_files.items) |f| try out.print(allocator, "compose {s}\n", .{f});
    }
    if (info.has_env_example or info.has_env_file) {
        try out.print(allocator, "\nenv:\n", .{});
        if (info.has_env_example) try out.print(allocator, "example .env.example\n", .{});
        if (info.has_env_file) try out.print(allocator, "file .env\n", .{});
    }
    if (info.scripts.items.len > 0) {
        try out.print(allocator, "\nscripts {s}:\n", .{info.package_manager});
        for (info.scripts.items) |s| try writeQuotedLine(allocator, &out, s);
    }
    return out.toOwnedSlice(allocator);
}

pub fn renderLock(allocator: std.mem.Allocator, cfg: ProjectConfig, tools: []const ResolvedTool, compose: []const FileCheck, env_checks: []const FileCheck, deps: []const DependencyCheck) ![]const u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(allocator);
    try out.print(allocator, "# Generated by tyx. Commit this file with project.tyx.\nlock 1\n", .{});
    if (tools.len > 0) {
        try out.print(allocator, "\ntools:\n", .{});
        for (tools) |t| {
            try out.print(allocator, "{s} requested {s} status {s}", .{ t.name, t.requested, t.status });
            if (t.version.len > 0) try out.print(allocator, " version {s}", .{t.version});
            if (std.mem.eql(u8, t.status, "present")) try out.print(allocator, " matches {}", .{t.matches});
            if (t.provider.len > 0) try out.print(allocator, " provider {s}", .{t.provider});
            try out.print(allocator, "\n", .{});
        }
    } else if (deps.len > 0) {
        try out.print(allocator, "\n", .{});
    }
    if (compose.len > 0) {
        try out.print(allocator, "\nservices:\n", .{});
        for (compose) |c| try out.print(allocator, "compose file {s} status {s}\n", .{ c.path, c.status });
    }
    if (env_checks.len > 0) {
        try out.print(allocator, "\nenv:\n", .{});
        for (env_checks) |c| try out.print(allocator, "{s} {s} status {s}\n", .{ c.kind, c.path, c.status });
    }
    if (deps.len > 0) {
        try out.print(allocator, "\ndependencies:\n", .{});
        for (deps) |d| try out.print(allocator, "{s} manifest {s} path {s} status {s}\n", .{ d.runner, d.manifest, d.path, d.status });
    }
    for (cfg.script_groups.items) |group| if (group.scripts.items.len > 0) {
        try out.print(allocator, "\nscripts {s}:\n", .{group.runner});
        for (group.scripts.items) |s| try writeQuotedLine(allocator, &out, s);
    };
    return out.toOwnedSlice(allocator);
}

fn writeQuotedLine(allocator: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) !void {
    if (std.mem.indexOfAny(u8, s, " \t") != null) {
        try out.print(allocator, "\"{s}\"\n", .{s});
    } else {
        try out.print(allocator, "{s}\n", .{s});
    }
}
